{% set data = load_setup_py_data() %}

package:
  name: appname
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - pydm

test:
  imports:
    - appname

about:
  home: https://github.com/pcdshub/pydm-application-template
  license: SLAC Open License
  summary: Generic pydm application template
