package:
  name: SLAC-LCLS-Stock-Management
  version: { { load_setup_py_data().get('version') } }

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - pyqt6
    - opencv
    - numpy
    - pathlib
    - typing
    - qasync
    - qrcode

test:
  imports:
    - stock_manager

about:
  home: https://github.com/pcdshub/stock-management.git
  license: SLAC Open License
  license_file: LICENSE
  summary: "SLAC LCLS stock management application with QR code support and simple UI."
