name: PCDS Standard Testing

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-standard.yml@52a413e9d77c09f9e7617c3a75fc19a7d6cf4e11
    secrets: inherit
    with:
      package-name: "stock_manager"
      testing-extras: ""
      conda-testing-extras: ""
      pip-testing-extras: ""
      use-setuptools-scm: true
